# Generated by Django 3.0.6 on 2020-06-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
